// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppDrawer: typeof import('./src/components/AppDrawer.vue')['default']
    ChatItem: typeof import('./src/components/ChatItem.vue')['default']
    ChatList: typeof import('./src/components/ChatList.vue')['default']
    ContactItem: typeof import('./src/components/ContactItem.vue')['default']
    ContactList: typeof import('./src/components/ContactList.vue')['default']
    LogoutButton: typeof import('./src/components/LogoutButton.vue')['default']
    MessageContainer: typeof import('./src/components/MessageContainer.vue')['default']
    MessageInputBox: typeof import('./src/components/MessageInputBox.vue')['default']
    MessageItem: typeof import('./src/components/MessageItem.vue')['default']
    MessageList: typeof import('./src/components/MessageList.vue')['default']
    QrCode: typeof import('./src/components/QrCode.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
